services:
  asr:
    image: lancelrq/qwen3-asr-service:latest
    # build:
    #   context: .
    #   tags:
    #     - lancelrq/qwen3-asr-service:latest
    ports:
      - "8765:8765"
    volumes:
      - ./asr-service/models:/app/models
      - ./asr-service/logs:/app/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command:
      - --model-size=0.6b        # 模型大小：0.6b / 1.7b
      - --device=auto             # 运行设备：auto / cuda / cpu
      - --model-source=modelscope # 下载源：modelscope / huggingface
      - --enable-align            # 启用对齐模型（不需要则改为 --no-align）
      # - --use-punc              # 启用标点恢复（按需开启）
      - --web                     # 启用 Web UI（访问 /web-ui）
      - --max-segment=5           # VAD 切片合并最大时长（秒）
    restart: unless-stopped
