services:
  asr:
    image: lancelrq/qwen3-asr-service:latest
    ports:
      - "8765:8765"
    environment:
      HF_ENDPOINT: https://hf-mirror.com
    volumes:
      - ./asr-service/models:/app/models
      - ./asr-service/logs:/app/logs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command:
      - --model-size=0.6b
      - --device=auto
      - --model-source=modelscope
      - --enable-align
      - --web
      - --max-segment=5
    restart: unless-stopped
